
// Types should be imported directly from ./content-types to avoid server action transformation issues
import type { Subject, Topic, Lesson } from "./content-types";

// Subject metadata (non-structural info that doesn't affect routing)
const SUBJECT_META: Record<string, { description: string; icon: string; color: string; label: string }> = {
  "artificial-intelligence": {
    description: "Master Artificial Intelligence from foundations to advanced agentic systems",
    icon: "ðŸ§ ",
    color: "from-indigo-500 to-purple-600",
    label: "Artificial Intelligence (AI)",
  },

  "computer-network": {
    description: "Learn how layered protocols, routing, switching, and transport mechanisms allow devices to communicate across local and wide-area networks.",
    icon: "CN",
    color: "from-neutral-700 to-neutral-900",
    label: "Computer Network",
  },
  "computer-organization-and-architecture": {
    description: "Study processor design, instruction execution, memory hierarchy, and the internal organization that makes a computer system work.",
    icon: "COA",
    color: "from-neutral-700 to-neutral-900",
    label: "Computer Organization and Architecture",
  },
  "operating-system": {
    description: "Understand process scheduling, memory management, file systems, and device coordination inside modern operating systems.",
    icon: "OS",
    color: "from-neutral-700 to-neutral-900",
    label: "Operating System",
  },
  "digital-electronics": {
    description: "Cover Boolean algebra, logic gates, combinational circuits, sequential circuits, and the digital hardware used in computation.",
    icon: "DE",
    color: "from-neutral-700 to-neutral-900",
    label: "Digital Electronics",
  },
  "signals-and-systems": {
    description: "Analyze continuous and discrete signals, system properties, convolution, sampling, and transform-based reasoning.",
    icon: "S&S",
    color: "from-neutral-700 to-neutral-900",
    label: "Signals & Systems",
  },
  "communication-systems": {
    description: "Study modulation, encoding, channel behavior, noise, and the flow of information through communication links.",
    icon: "CS",
    color: "from-neutral-700 to-neutral-900",
    label: "Communication Systems",
  },
  "database-management-system": {
    description: "Explore relational modeling, normalization, transactions, indexing, and query processing in database systems.",
    icon: "DBMS",
    color: "from-neutral-700 to-neutral-900",
    label: "Database Management System",
  },
  "control-systems": {
    description: "Learn feedback, stability, transfer functions, and frequency response techniques for dynamic system analysis.",
    icon: "CTRL",
    color: "from-neutral-700 to-neutral-900",
    label: "Control Systems",
  },
  "compiler-design": {
    description: "Understand lexical analysis, parsing, semantic analysis, optimization, and code generation in compilers.",
    icon: "CD",
    color: "from-neutral-700 to-neutral-900",
    label: "Compiler Design",
  },  dsa: {
    description: "Master Data Structures & Algorithms from fundamentals to advanced techniques",
    icon: "âš¡",
    color: "from-orange-500 to-red-600",
    label: "Data Structures & Algorithms",
  },

};

// Topic sort order for specific subjects
const TOPIC_ORDER: Record<string, string[]> = {
  dsa: [
    "cpp-fundamentals",
    "problem-solving-basics",
    "time-space-complexity",
    "arrays",
    "strings",
    "searching-sorting",
    "hashing",
    "recursion-backtracking",
    "linked-list",
    "stack-queue",
    "graphs",
    "dynamic-programming",
  ],
    "artificial-intelligence": [
    "01-ai-foundations",
    "02-machine-learning",
    "03-deep-learning",
    "04-transformers",
    "05-nlp",
    "06-computer-vision",
    "07-generative-ai",
    "08-multimodal-ai",
    "09-reinforcement-learning",
    "10-rag-and-memory",
    "11-agentic-ai",
    "12-fine-tuning-and-adaptation",
    "13-mlops",
    "14-vector-embeddings",
    "15-evaluation-and-benchmarking",
    "16-ai-safety-and-robustness",
    "17-speech-and-audio",
    "18-time-series-and-forecasting",
    "19-recommendation-systems",
    "20-advanced-research"
  ],

  "computer-network": [
    "introduction",
    "physical-layer",
    "data-link-layer",
    "network-layer",
    "transport-layer",
    "application-layer",
    "wireless-networks",
    "network-security",
    "advanced-networking",
    "practical-labs",
    "interview-prep"
  ],
  "computer-organization-and-architecture": ["coa"],
  "operating-system": [
    "introduction-to-os",
    "process-management",
    "synchronization",
    "memory-management",
    "file-systems",
    "security-and-protection",
    "linux-and-unix",
    "virtualization-and-cloud",
    "case-studies",
    "advanced-operating-systems"
  ],
  "digital-electronics": ["digital-electronics"],
  "signals-and-systems": ["signals-and-systems"],
  "communication-systems": ["communication-systems"],
  "database-management-system": ["dbms"],
  "control-systems": ["control-systems"],
  "compiler-design": ["compiler-design"],
};

// Topic display name mapping
const TOPIC_LABELS: Record<string, string> = {
  "cpp-fundamentals": "C++ Fundamentals",
  "problem-solving-basics": "Problem Solving Basics",
  "time-space-complexity": "Time & Space Complexity",
  arrays: "Arrays",
  strings: "Strings",
  "recursion-backtracking": "Recursion & Backtracking",
  "linked-list": "Linked List",
  "stack-queue": "Stack & Queue",
  "searching-sorting": "Searching & Sorting",
  hashing: "Hashing",
  trees: "Trees",
  graphs: "Graphs",
  "dynamic-programming": "Dynamic Programming",
  "ai-foundations": "AI Foundations",
  "machine-learning": "Machine Learning",
  "deep-learning": "Deep Learning",
  "transformers": "Transformers",
  nlp: "Natural Language Processing (NLP)",
  "computer-vision": "Computer Vision (CV)",
  "generative-ai": "Generative AI",
  "neural-networks": "Neural Networks",
  "agentic-ai": "Agentic AI",
  "reinforcement-learning": "Reinforcement Learning (RL)",
  "deep-reinforcement-learning": "Deep Reinforcement Learning (DRL)",
  "multimodal-ai": "Multimodal AI",
  mlops: "MLOps",
  "fine-tuning-adaptation": "Fine-Tuning & Adaptation",
  "rag-memory": "RAG & Memory",
  "advanced-research": "Advanced Research",
  cn: "CN â€” Computer Networks",
  coa: "COA â€” Computer Organization & Architecture",
  os: "OS â€” Operating Systems",
    "introduction-to-os": "Introduction to OS",
  "process-management": "Process Management",
  "synchronization": "Synchronization",
  "memory-management": "Memory Management",
  "file-systems": "File Systems",
  "security-and-protection": "Security and Protection",
  "linux-and-unix": "Linux and Unix",
  "virtualization-and-cloud": "Virtualization and Cloud",
  "case-studies": "Case Studies",
  "advanced-operating-systems": "Advanced Operating Systems",
  "digital-electronics": "Digital Electronics",
  "signals-and-systems": "Signals & Systems",
  "communication-systems": "Communication Systems",
  dbms: "DBMS â€” Database Management Systems",
  "control-systems": "Control Systems",
  "compiler-design": "Compiler Design",
  "introduction": "Introduction",
  "physical-layer": "Physical Layer",
  "data-link-layer": "Data Link Layer",
  "network-layer": "Network Layer",
  "transport-layer": "Transport Layer",
  "application-layer": "Application Layer",
  "wireless-networks": "Wireless Networks",
  "network-security": "Network Security",
  "advanced-networking": "Advanced Networking",
  "practical-labs": "Practical Labs",
  "interview-prep": "Interview Prep",



};

// Topic descriptions for comprehensive definitions
const TOPIC_DESCRIPTIONS: Record<string, string> = {
  "cpp-fundamentals": "Dive deep into the foundational constructs of C++ programming. This module covers core syntax, data types, control flow mechanisms, object-oriented programming paradigms, and the Standard Template Library (STL). Master memory management, pointers, and performance optimization techniques essential for writing robust, high-performance algorithms.",
  "problem-solving-basics": "Develop a structured, analytical mindset required to tackle complex computational problems. Learn essential frameworks for decomposing problem statements, analyzing edge cases, performing dry runs, and utilizing mathematical observations. This module transitions you from brute-force thinking to recognizing optimal algorithmic patterns.",
  "time-space-complexity": "Master the theoretical foundations of algorithm analysis using Big-O, Big-Omega, and Big-Theta notation. Gain an intuitive understanding of how algorithmic execution time and memory consumption scale with input size. Learn to identify bottlenecks, perform amortized analysis, and make critical trade-offs between time efficiency and spatial footprints.",
  "arrays": "Explore the most fundamental contiguous data structure. This module covers memory allocation, rapid random access, and complex in-place manipulations. Master essential techniques such as two-pointer approaches, sliding windows, prefix sums, and Kadane's algorithm to solve high-frequency interview problems with optimal complexity.",
  "strings": "Uncover the intricacies of character data manipulation and sequence processing. This module dives into lexicographical operations, pattern matching algorithms (KMP, Rabin-Karp, Z-Algorithm), and string hashing. Learn to handle edge cases in parsing, palindrome detection, and complex substring optimization efficiently.",
  "recursion-backtracking": "Embrace the power of self-referential functions and state-space exploration. Start from basic recurrence relations and progress to complex backtracking frameworks. Master the art of generating permutations, combinations, and subsets while utilizing bounding functions and pruning techniques to optimize depth-first search trees.",
  "linked-list": "Delve into dynamic memory structures where nodes are connected via discrete pointers. This module covers singly, doubly, and circular linked lists. Master intricate pointer manipulations required for cycle detection, reversing sub-lists, and merging operations, fundamentally preparing you for complex graph and tree traversals.",
  "stack-queue": "Understand LIFO and FIFO data management principles. Implement stacks and queues using arrays and linked lists, and explore advanced variants like monotonic stacks, priority queues, and deques. Learn to apply these structures to evaluate expressions, track state histories, and solve complex sliding window and nearest-element problems.",
  "searching-sorting": "Master the art of efficiently locating data and imposing order. Journey beyond linear search to explore binary search on answer spaces and ternary search algorithms. Compare the internal mechanics of Quick Sort, Merge Sort, and Heap Sort, deeply analyzing their stability, in-place characteristics, and optimal use cases in competitive programming.",
  "hashing": "Unlock the power of expected O(1) time complexity operations using hash tables. This module explores collision resolution strategies, load factors, and cryptographic hash functions. Master the use of frequency maps, sets, and rolling hashes to solve complex subarray, permutation, and substring problems with lightning-fast performance.",
  "trees": "Navigate the hierarchical branching structures that power modern databases and routing algorithms. Journey from fundamental binary trees and BSTs to self-balancing structures like AVL and Red-Black trees. Master exhaustive traversal algorithms (DFS, BFS), LCA computation, and advanced structures like Tries, Segment Trees, and Fenwick Trees.",
  "graphs": "Conquer the ultimate non-linear data structures used to model real-world networks. This comprehensive module covers graph representations, traversal algorithms, cycle detection, and topological sorting. Master advanced algorithms for shortest paths (Dijkstra, Bellman-Ford), Minimum Spanning Trees (Kruskal, Prim), and Strongly Connected Components.",
  "dynamic-programming": "Transcend brute-force recursion by mastering state tabulation and memoization. This advanced module teaches you to identify optimal substructure and overlapping subproblems. Master 1D and 2D DP grids, knapsack variants, DP on strings, DP on trees, and advanced state-space optimization techniques to solve the most daunting algorithmic challenges.",

  "ai-foundations": "Explore the foundational principles of artificial intelligence, covering historical contexts, basic heuristic search algorithms, and the underlying philosophy of intelligent agents.",
  "machine-learning": "Master the core algorithms that enable computers to learn from data, including linear regression, classification models, ensemble methods, and fundamental statistical learning theory.",
  "deep-learning": "Dive into the mechanics of artificial neural networks, backpropagation, and activation functions. Understand how deep architectures capture hierarchical representations of complex data.",
  "transformers": "Understand the revolutionary attention mechanisms and transformer architectures that power modern Large Language Models, enabling unprecedented capabilities in sequence-to-sequence tasks.",
  "nlp": "Explore techniques for processing and understanding human language, from basic tokenization and word embeddings to advanced semantic analysis and contextual language modeling.",
  "computer-vision": "Delve into the algorithms that allow machines to interpret visual data. Learn about Convolutional Neural Networks (CNNs), image segmentation, object detection, and facial recognition.",
  "generative-ai": "Discover the algorithms behind creative AI, including Generative Adversarial Networks (GANs), Variational Autoencoders (VAEs), and diffusion models capable of synthesizing novel content.",
  "agentic-ai": "Study the cutting-edge frameworks that empower AI systems to act autonomously, reason through multi-step workflows, interact with environments, and utilize external tools dynamically.",
  "reinforcement-learning": "Master the paradigm of learning through trial and error. Explore Markov Decision Processes, Q-learning, and policy gradients to train agents that maximize cumulative rewards.",
  "deep-reinforcement-learning": "Combine deep neural networks with reinforcement learning to tackle incredibly complex state spaces, powering breakthroughs in robotics and superhuman game-playing AI.",
  "multimodal-ai": "Explore systems capable of simultaneously processing and synthesizing multiple data modalitiesâ€”such as text, vision, and audioâ€”to achieve richer and more human-like contextual understanding.",
  "mlops": "Learn the engineering practices required to deploy, monitor, and scale machine learning models in production environments, ensuring robust data pipelines and model lifecycle management.",
  "fine-tuning-adaptation": "Master the techniques for adapting massive pre-trained models to specialized domains using parameter-efficient fine-tuning (PEFT), LoRA, and domain-specific knowledge injection.",
  "rag-memory": "Discover Retrieval-Augmented Generation (RAG) and long-term memory architectures that allow AI models to access, synthesize, and reason over vast external knowledge bases.",
  "advanced-research": "Engage with the absolute frontiers of AI research, exploring speculative architectures, theoretical alignment problems, and the pursuit of Artificial General Intelligence (AGI).",
  cn: "Learn how layered protocols, routing, switching, and transport mechanisms allow devices to communicate across local and wide-area networks.",
  coa: "Study processor design, instruction execution, memory hierarchy, and the internal organization that makes a computer system work.",
  os: "Understand process scheduling, memory management, file systems, and device coordination inside modern operating systems.",
  "digital-electronics": "Cover Boolean algebra, logic gates, combinational circuits, sequential circuits, and the digital hardware used in computation.",
  "signals-and-systems": "Analyze continuous and discrete signals, system properties, convolution, sampling, and transform-based reasoning.",
  "communication-systems": "Study modulation, encoding, channel behavior, noise, and the flow of information through communication links.",
  dbms: "Explore relational modeling, normalization, transactions, indexing, and query processing in database systems.",
  "control-systems": "Learn feedback, stability, transfer functions, and frequency response techniques for dynamic system analysis.",
  "compiler-design": "Understand lexical analysis, parsing, semantic analysis, optimization, and code generation in compilers."
};

// Manual sort order for lessons in specific topics
const LESSON_ORDER: Record<string, string[]> = {
  "ai-foundations": [
    "00-theory-history-of-ai",
    "00-theory-mathematical-foundations-overview",
    "01-math-linear-algebra-vectors",
    "01-theory-vector-spaces-and-fields",
    "02-math-linear-algebra-dot-products",
    "02-theory-inner-product-spaces",
    "03-math-linear-algebra-eigenvalues",
    "03-theory-spectral-theorem-proofs",
    "04-math-linear-algebra-decomposition",
    "04-theory-svd-derivation",
    "05-math-calculus-derivatives",
    "06-math-calculus-chain-rule",
    "07-math-calculus-partial-derivatives",
    "08-math-calculus-optimization",
    "08-theory-convexity-and-optimality-conditions",
    "09-math-probability-distributions",
    "09-theory-measure-theoretic-probability",
    "10-math-probability-conditional",
    "11-math-probability-bayes",
    "11-theory-bayesian-inference-foundations",
    "12-math-probability-expectation",
    "12-theory-laws-of-large-numbers-clt",
    "13-math-statistics-hypothesis-testing",
    "13-theory-statistical-decision-theory",
    "14-math-statistics-regression-analysis",
    "15-math-statistics-sampling",
    "16-math-statistics-information-theory",
    "17-programming-python-oop",
    "18-programming-python-functional",
    "19-programming-python-concurrency",
    "20-programming-data-structures-arrays-trees",

  ],
  "machine-learning": [
    "00-theory-statistical-learning-theory",
    "00-theory-pac-learning-and-vc-dimension",
    "01-supervised-regression-linear",
    "01-theory-ols-derivation-and-gauss-markov",
    "02-supervised-regression-polynomial",
    "03-supervised-regression-ridge-lasso",
    "03-theory-regularization-and-bias-variance-tradeoff",
    "04-supervised-classification-logistic",
    "04-theory-logistic-regression-mle-derivation",
    "05-supervised-classification-knn",
    "06-supervised-classification-naive-bayes",
    "06-theory-naive-bayes-probabilistic-foundations",
    "07-supervised-classification-svm",
    "07-theory-svm-lagrangian-and-kernel-trick",
    "08-supervised-ensemble-random-forest",
    "08-theory-bias-variance-in-ensembles",
    "09-supervised-ensemble-gradient-boosting",
    "09-theory-functional-gradient-descent",
    "10-supervised-ensemble-xgboost-lightgbm",
    "11-supervised-ensemble-bagging-stacking",
    "11-theory-boosting-convergence-proofs",
    "12-theory-kmeans-convergence-and-optimality",
    "12-unsupervised-clustering-kmeans",
    "13-unsupervised-clustering-dbscan",
    "14-unsupervised-clustering-hierarchical",
    "15-theory-pca-variance-maximization-proof",
    "15-unsupervised-dimensionality-pca",
    "16-theory-tsne-kl-divergence-objective",
    "16-unsupervised-dimensionality-tsne",
    "17-theory-umap-riemannian-geometry-foundations",
    "17-unsupervised-dimensionality-umap",
    "18-unsupervised-association-apriori",
    "19-unsupervised-association-fpgrowth",
    "20-semi-supervised-self-training",
    "21-semi-supervised-pseudo-labeling",
    "22-semi-supervised-label-propagation",
    "22-theory-graph-based-semi-supervised-learning",
    "23-engineering-feature-engineering",
    "24-engineering-cross-validation",
    "24-theory-generalization-bounds-and-cross-validation",
    "25-engineering-hyperparameter-tuning",
    "25-theory-bayesian-optimization-theory",
    "26-engineering-class-imbalance",
    "27-engineering-pipelines",
    "17-neural-networks-mlp",
    "18-neural-networks-cnn",
    "19-reinforcement-learning-qlearning",
    "20-reinforcement-learning-dqn"
  ],
  "cpp-fundamentals": [
    "introduction-to-cpp",
    "structure-of-cpp-program",
    "compilation-process",
    "input-output",
    "comments-in-cpp",
    "variables",
    "data-types",
    "type-modifiers",
    "constants-literals",
    "keywords-identifiers",
    "operators",
    "arithmetic-operators",
    "relational-operators",
    "logical-operators",
    "bitwise-operators",
    "assignment-operators",
    "increment-decrement-operators",
    "ternary-operator",
    "operator-precedence",
    "type-casting",
    "escape-sequences",
    "conditional-statements",
    "if-statement",
    "if-else-statement",
    "nested-if",
    "else-if-ladder",
    "switch-statement",
    "loops",
    "for-loop",
    "while-loop",
    "do-while-loop",
    "nested-loops",
    "loop-control",
    "functions",
    "function-declaration-definition",
    "function-calling",
    "parameters-arguments",
    "return-values",
    "default-arguments",
    "inline-functions",
    "function-overloading",
    "recursion",
    "variable-scope",
    "local-variables",
    "global-variables",
    "storage-classes",
    "arrays",
    "one-d-arrays",
    "two-d-arrays",
    "multidimensional-arrays",
    "character-arrays",
    "strings",
    "c-style-strings",
    "string-class",
    "string-functions",
    "pointers",
    "pointer-basics",
    "pointer-arithmetic",
    "pointers-and-arrays",
    "null-pointers",
    "dynamic-memory-allocation",
    "references",
    "reference-variables",
    "pass-by-reference",
    "structures",
    "unions",
    "enumerations",
    "typedef",
    "namespaces",
    "header-files",
    "preprocessor-directives",
    "macros",
    "file-handling",
    "reading-from-files",
    "writing-to-files",
    "oop-basics",
    "classes-objects",
    "access-specifiers",
    "constructors",
    "destructors",
    "copy-constructor",
    "this-pointer",
    "static-members",
    "friend-function",
    "inheritance",
    "types-of-inheritance",
    "polymorphism",
    "function-overriding",
    "virtual-functions",
    "abstraction",
    "encapsulation",
    "operator-overloading",
    "exception-handling",
    "templates",
    "function-templates",
    "class-templates",
    "stl-introduction",
    "vectors",
    "pairs",
    "iterators",
    "stl-algorithms",
    "stl-stack",
    "stl-queue",
    "stl-set",
    "stl-map",
    "stl-priority-queue",
    "stl-deque",
    "lambda-functions",
    "auto-keyword",
    "range-based-loops",
    "smart-pointers",
    "time-complexity-basics",
  ],
  "problem-solving-basics": [
    "introduction-to-problem-solving",
    "problem-understanding",
    "input-output-analysis",
    "constraints-analysis",
    "dry-run-technique",
    "brute-force-approach",
    "optimized-approach-thinking",
    "pattern-recognition",
    "breaking-problems-subproblems",
    "logical-thinking",
    "algorithmic-thinking",
    "pseudocode",
    "flowcharts",
    "basic-mathematics",
    "number-properties",
    "prime-numbers",
    "factors-and-multiples",
    "gcd-and-lcm",
    "modular-arithmetic-basics",
    "binary-number-basics",
    "bit-manipulation-basics",
    "time-complexity-basics",
    "space-complexity-basics",
    "best-average-worst-case",
    "iterative-thinking",
    "recursive-thinking",
    "simulation-problems",
    "greedy-basics",
    "two-pointer-basics",
    "sliding-window-basics",
    "prefix-sum-basics",
    "frequency-counting",
    "hashing-basics",
    "sorting-basics",
    "searching-basics",
    "binary-search-basics",
    "matrix-traversal-basics",
    "string-manipulation-basics",
    "array-manipulation-basics",
    "backtracking-basics",
    "divide-and-conquer-basics",
    "edge-case-handling",
    "overflow-handling",
    "debugging-techniques",
    "test-case-generation",
    "competitive-programming-basics",
    "stl-basics",
    "input-optimization",
    "code-readability",
    "problem-solving-patterns",
    "observation-building",
    "mathematical-observation",
    "constructive-thinking",
    "ad-hoc-problems",
    "implementation-problems",
    "optimization-techniques",
    "practice-strategy",
  ],
  "time-space-complexity": [
    "introduction-to-time-complexity",
    "introduction-to-space-complexity",
    "why-complexity-analysis",
    "input-size-growth-rate",
    "best-case-complexity",
    "average-case-complexity",
    "worst-case-complexity",
    "big-o-notation",
    "big-omega-notation",
    "big-theta-notation",
    "constant-time",
    "logarithmic-time",
    "linear-time",
    "linearithmic-time",
    "quadratic-time",
    "cubic-time",
    "exponential-time",
    "factorial-time",
    "complexity-comparison",
    "rules-for-calculating",
    "ignore-constants",
    "ignore-lower-order",
    "complexity-of-loops",
    "complexity-nested-loops",
    "complexity-sequential-loops",
    "complexity-recursion",
    "recurrence-relation-basics-complexity",
    "master-theorem-basics",
    "space-complexity-basics-tsc",
    "auxiliary-space",
    "input-space",
    "recursive-stack-space",
    "inplace-algorithms-complexity",
    "time-space-tradeoff",
    "complexity-arrays",
    "complexity-strings",
    "complexity-linked-lists",
    "complexity-stack",
    "complexity-queue",
    "complexity-hashing",
    "complexity-trees",
    "complexity-heap",
    "complexity-graph",
    "complexity-sorting",
    "complexity-searching",
    "amortized-complexity",
    "iterative-vs-recursive",
    "complexity-stl-containers",
    "complexity-stl-algorithms",
    "optimization-techniques-tsc",
    "brute-force-vs-optimized",
    "identifying-bottlenecks",
    "tle-basics",
    "mle-basics",
    "choosing-efficient-algorithms",
    "complexity-competitive-programming",
    "dry-run-complexity",
    "practice-complexity",
  ],
  "recursion-backtracking": [
    "introduction-to-recursion",
    "recursive-thinking",
    "base-case",
    "recursive-case",
    "recursive-function-calls",
    "call-stack",
    "stack-overflow",
    "dry-run-recursion",
    "tail-recursion",
    "head-recursion",
    "tree-recursion",
    "indirect-recursion",
    "nested-recursion",
    "parameterized-recursion",
    "functional-recursion",
    "recurrence-relation-basics",
    "time-complexity-recursion",
    "space-complexity-recursion",
    "recursive-pattern-problems",
    "print-numbers",
    "sum-of-n-numbers",
    "factorial",
    "fibonacci",
    "power-calculation",
    "reverse-array-recursion",
    "reverse-string-recursion",
    "palindrome-check-recursion",
    "binary-search-recursion",
    "recursion-on-arrays",
    "recursion-on-strings",
    "subsequence-problems",
    "generate-all-subsequences",
    "generate-all-subsets",
    "generate-power-set",
    "pick-not-pick",
    "multiple-recursion-calls",
    "backtracking-introduction",
    "recursion-vs-backtracking",
    "backtracking-template",
    "decision-tree-visualization",
    "state-space-tree",
    "undo-backtrack-step",
    "constraint-checking",
    "generate-all-permutations",
    "permutations-duplicates",
    "combination-sum",
    "combination-sum-ii",
    "subset-sum-recursion",
    "letter-combinations",
    "generate-parentheses",
    "n-queens",
    "rat-in-a-maze",
    "sudoku-solver",
    "word-search",
    "m-coloring",
    "knights-tour",
    "maze-solving",
    "partition-problems",
    "palindrome-partitioning-recursion",
    "restore-ip-addresses",
    "expression-add-operators",
    "backtracking-on-grids",
    "backtracking-on-strings",
    "backtracking-on-arrays",
    "branch-and-bound-basics",
    "recursion-tree-method",
    "memoization-basics",
    "recursive-dp-intro",
    "practice-patterns-recursion",
    "practice-patterns-backtracking",
  ],
  "arrays": [
    "array-introduction",
    "array-traversal",
    "array-input-output",
    "reverse-array",
    "linear-search",
    "binary-search",
    "find-min-max",
    "move-zeroes",
    "remove-duplicates",
    "two-sum",
    "sort-colors",
    "kadane-algorithm",
    "maximum-subarray-sum",
    "prefix-sum-basics",
    "range-sum-query",
    "equilibrium-index",
    "bubble-sort",
    "majority-element",
    "product-of-array-except-self",
    "next-permutation",
    "merge-intervals",
    "trapping-rain-water",
    "container-with-most-water",
    "maximum-product-subarray",
    "longest-subarray-k",
    "subarray-sum-equals-k",
    "fixed-window-sum",
    "minimum-window-substring",
    "largest-number",
  ],
  "linked-list": [
    "add-two-numbers",
    "advantages-disadvantages",
    "check-palindrome",
    "circular-doubly-linked-list",
    "circular-linked-list",
    "circular-operations",
    "clone-with-random-pointer",
    "delete-nth-node-from-end",
    "deletion-by-position",
    "deletion-by-value",
    "deletion-from-beginning",
    "deletion-from-end",
    "deletion-in-dll",
    "detect-loop",
    "doubly-linked-list",
    "doubly-operations",
    "dynamic-memory-allocation",
    "flatten-linked-list",
    "floyd-cycle-detection",
    "header-linked-list",
    "insertion-at-beginning",
    "insertion-at-end",
    "insertion-at-position",
    "insertion-in-dll",
    "intersection-of-lists",
    "intersection-point",
    "introduction-to-linked-list",
    "iterator-linked-list",
    "length",
    "linked-list-basics",
    "loop-start-point",
    "lru-using-dll",
    "memory-representation",
    "merge-sort-linked-list",
    "merge-sorted-lists",
    "middle-of-linked-list",
    "multiply-linked-lists",
    "node-structure",
    "nth-node-from-end",
    "odd-even-linked-list",
    "partition-linked-list",
    "polynomial-linked-list",
    "practice-patterns",
    "queue-using-linked-list",
    "recursive-reversal",
    "remove-duplicates-sorted",
    "remove-duplicates-unsorted",
    "remove-loop",
    "reverse-dll",
    "reverse-in-k-groups",
    "reverse-linked-list",
    "rotate-linked-list",
    "searching",
    "segregate-even-odd",
    "singly-linked-list",
    "skip-list-basics",
    "sort-linked-list",
    "sparse-matrix-linked-list",
    "stack-using-linked-list",
    "stl-list",
    "swap-nodes-in-pairs",
    "traversal",
    "types-of-linked-list",
    "updating-nodes",
    "xor-linked-list-basics",
  ],

  "searching-sorting": [
    "introduction-to-searching",
    "linear-search-searching",
    "binary-search-searching",
    "binary-search-descending",
    "order-agnostic-binary-search",
    "lower-bound",
    "upper-bound",
    "floor-and-ceil",
    "first-occurrence",
    "last-occurrence",
    "count-occurrences",
    "search-insert-position",
    "binary-search-on-answer",
    "peak-element",
    "search-in-rotated-array",
    "search-in-nearly-sorted",
    "min-in-rotated-array",
    "single-element-sorted",
    "sqrt-binary-search",
    "nth-root-binary-search",
    "allocate-minimum-pages",
    "aggressive-cows",
    "painters-partition",
    "koko-eating-bananas",
    "capacity-to-ship-packages",
    "median-two-sorted-arrays",
    "search-2d-matrix",
    "row-with-max-ones",
    "introduction-to-sorting",
    "stability-in-sorting",
    "inplace-vs-outplace-sorting",
    "adaptive-sorting",
    "internal-vs-external-sorting",
    "bubble-sort",
    "selection-sort",
    "insertion-sort",
    "merge-sort",
    "quick-sort",
    "heap-sort",
    "counting-sort",
    "radix-sort",
    "bucket-sort",
    "shell-sort",
    "recursive-sorting",
    "iterative-sorting",
    "partitioning-techniques",
    "lomuto-partition",
    "hoare-partition",
    "dutch-national-flag",
    "quick-select",
    "kth-smallest-element",
    "kth-largest-element",
    "sort-012",
    "merge-two-sorted-arrays",
    "inversion-count",
    "reverse-pairs",
    "external-sorting-basics",
    "stl-sort",
    "custom-comparator",
    "stable-sort",
    "partial-sort",
    "binary-search-stl",
    "lower-upper-bound-stl",
    "two-pointer-sorting",
    "greedy-sorting",
    "practice-patterns-searching",
    "practice-patterns-sorting",
  ],
  "stack-queue": [
    "introduction-to-stack",
    "stack-data-structure",
    "lifo-principle",
    "stack-operations",
    "push-operation",
    "pop-operation",
    "peek-top-operation",
    "isempty-isfull",
    "stack-arrays",
    "stack-linked-list",
    "dynamic-stack",
    "complexity-stack",
    "applications-stack",
    "balanced-parentheses",
    "valid-parentheses",
    "infix-expression",
    "prefix-expression",
    "postfix-expression",
    "infix-to-postfix",
    "infix-to-prefix",
    "postfix-to-infix",
    "prefix-to-infix",
    "evaluate-postfix",
    "evaluate-prefix",
    "recursion-call-stack",
    "backtracking-stack",
    "monotonic-stack",
    "next-greater-element",
    "next-smaller-element",
    "previous-greater-element",
    "previous-smaller-element",
    "stock-span",
    "largest-rectangle-histogram",
    "maximal-rectangle",
    "trapping-rain-water",
    "min-stack",
    "special-stack",
    "stack-using-queue",
    "two-stack-one-array",
    "multiple-stack-problems",
    "introduction-to-queue",
    "queue-data-structure",
    "fifo-principle",
    "queue-operations",
    "enqueue-operation",
    "dequeue-operation",
    "front-and-rear",
    "queue-arrays",
    "queue-linked-list",
    "circular-queue",
    "dynamic-queue",
    "deque-basics",
    "priority-queue-intro",
    "queue-using-stack",
    "stack-using-queue-queue",
    "applications-queue",
    "cpu-scheduling",
    "printer-queue",
    "bfs-using-queue",
    "sliding-window-max",
    "first-negative-window",
    "circular-tour",
    "lru-cache-queue",
    "k-queue-one-array",
    "priority-queue-heap",
    "stl-stack",
    "stl-queue",
    "stl-deque",
    "stl-priority-queue-stl",
    "monotonic-queue",
    "practice-patterns-stack",
    "practice-patterns-queue",
  ],
  strings: [
    "introduction-to-strings",
    "character-arrays-strings",
    "string-input-output",
    "string-traversal",
    "string-length",
    "string-concatenation",
    "string-comparison",
    "string-copy",
    "reverse-string",
    "palindrome-string",
    "toggle-case",
    "case-conversion",
    "remove-spaces",
    "count-vowels-consonants",
    "frequency-of-characters",
    "ascii-values",
    "character-hashing-strings",
    "string-searching",
    "substrings",
    "subsequence-vs-substring",
    "string-sorting",
    "lexicographical-order",
    "anagram-check",
    "rotate-string",
    "string-compression",
    "run-length-encoding",
    "remove-duplicates-string",
    "longest-common-prefix",
    "longest-palindromic-substring",
    "longest-palindromic-subsequence",
    "count-palindromic-substrings",
    "string-matching-basics",
    "naive-pattern-matching",
    "rabin-karp-algorithm-strings",
    "kmp-algorithm",
    "z-algorithm",
    "prefix-function-lps",
    "string-hashing-strings",
    "polynomial-rolling-hash-strings",
    "double-hashing-strings",
    "pattern-searching-problems",
    "wildcard-matching-strings",
    "regular-expression-basics",
    "sliding-window-strings",
    "longest-substring-no-repeat",
    "minimum-window-substring",
    "permutation-in-string",
    "group-anagrams-strings",
    "count-and-say",
    "string-to-integer",
    "integer-to-string",
    "string-streams",
    "tokenization",
    "split-string",
    "parsing-strings",
    "compare-version-numbers",
    "roman-to-integer",
    "integer-to-roman",
    "multiply-large-numbers",
    "binary-string-problems",
    "parentheses-string-problems",
    "balanced-string-problems",
    "edit-distance-strings",
    "distinct-subsequences-strings",
    "string-dp-basics",
    "trie-basics-strings",
    "suffix-array-basics",
    "suffix-trie-basics",
    "stl-string-functions",
    "practice-patterns-strings",
  ],
  trees: [
    "introduction-to-trees",
    "tree-terminology",
    "root-node",
    "parent-node",
    "child-node",
    "sibling-node",
    "leaf-node",
    "internal-node",
    "ancestor-descendant",
    "degree-of-node",
    "height-of-tree",
    "depth-of-node",
    "level-of-node",
    "subtree",
    "types-of-trees",
    "binary-tree",
    "full-binary-tree",
    "complete-binary-tree",
    "perfect-binary-tree",
    "balanced-binary-tree",
    "degenerate-binary-tree",
    "skewed-binary-tree",
    "bst-basics",
    "avl-tree",
    "red-black-tree",
    "heap-basics",
    "trie-basics",
    "segment-tree-basics",
    "fenwick-tree-basics",
    "n-ary-tree",
    "tree-representation",
    "array-representation",
    "linked-representation",
    "tree-traversal-basics",
    "dfs-traversal",
    "bfs-traversal",
    "preorder-traversal",
    "inorder-traversal",
    "postorder-traversal",
    "level-order-traversal",
    "recursive-traversals",
    "iterative-traversals",
    "morris-traversal",
    "binary-tree-construction",
    "construct-from-traversals",
    "serialize-deserialize",
    "count-nodes",
    "sum-of-nodes",
    "height-binary-tree",
    "diameter-binary-tree",
    "max-depth",
    "min-depth",
    "balanced-binary-tree-check",
    "identical-trees",
    "symmetric-tree",
    "mirror-tree",
    "invert-binary-tree",
    "lca-binary-tree",
    "path-in-trees",
    "root-to-node-path",
    "root-to-leaf-paths",
    "max-path-sum",
    "children-sum-property",
    "boundary-traversal",
    "vertical-order-traversal",
    "top-view",
    "bottom-view",
    "left-view",
    "right-view",
    "zigzag-traversal",
    "diagonal-traversal",
    "search-in-bst",
    "insert-in-bst",
    "delete-in-bst",
    "floor-in-bst",
    "ceil-in-bst",
    "kth-smallest-bst",
    "kth-largest-bst",
    "validate-bst",
    "lca-bst",
    "inorder-successor-predecessor",
    "bst-iterator",
    "bst-simulator",
    "recover-bst",
    "merge-two-bsts",
    "min-heap",
    "max-heap",
    "heap-operations",
    "heapify",
    "build-heap",
    "heap-sort",
    "priority-queue",
    "kth-largest-smallest-heap",
    "merge-k-sorted-arrays",
    "merge-k-sorted-lists",
    "insert-in-trie",
    "search-in-trie",
    "prefix-search",
    "word-dictionary",
    "lcp-using-trie",
    "range-sum-query",
    "range-min-query",
    "lazy-propagation",
    "prefix-sum-queries",
    "update-queries",
    "tree-dp-basics-tree",
    "dp-on-trees",
    "binary-lifting",
    "euler-tour",
    "heavy-light-decomposition",
    "dsu-tree",
    "practice-patterns-trees",
  ],
  hashing: [
    "introduction-to-hashing",
    "need-for-hashing",
    "hash-function",
    "good-hash-function",
    "hash-table",
    "direct-addressing",
    "collision-in-hashing",
    "collision-resolution",
    "separate-chaining",
    "open-addressing",
    "linear-probing",
    "quadratic-probing",
    "double-hashing",
    "rehashing",
    "load-factor",
    "time-complexity-hashing",
    "hashmap-unordered-map",
    "hashset-unordered-set",
    "frequency-array",
    "frequency-map",
    "counting-frequencies",
    "prefix-sum-hashing",
    "hashing-pair-problems",
    "duplicate-detection",
    "subarray-problems-hashing",
    "longest-subarray-sum-k",
    "count-subarrays-sum-k",
    "longest-consecutive-sequence",
    "two-sum-hashing",
    "three-sum-basics",
    "group-anagrams",
    "first-non-repeating-char",
    "sliding-window-hashing",
    "string-hashing-intro",
    "character-hashing",
    "integer-hashing",
    "custom-hash-functions",
    "ordered-vs-unordered-map",
    "set-vs-unordered-set",
    "multiset-unordered-multiset",
    "hashing-in-stl",
    "bucket-concept",
    "iterating-hashmaps",
    "hashing-for-caching",
    "lru-cache-basics",
    "polynomial-rolling-hash",
    "string-hashing",
    "rabin-karp-algorithm",
    "double-hashing-strings",
    "hash-collision-strings",
    "prefix-hashing",
    "pattern-matching-hashing",
    "bitmask-hashing",
    "coordinate-compression-hashing",
    "hashing-greedy-problems",
    "hashing-binary-search-problems",
    "hashing-practice-patterns",
  ],
  graphs: [
    "graph-definition",
    "vertices-and-edges",
    "graph-degrees",
    "types-of-graphs",
    "adjacency-list",
    "adjacency-matrix",
    "bfs",
    "dfs",
    "connected-components",
    "flood-fill",
    "number-of-islands",
    "cycle-detection-undirected",
    "cycle-detection-directed",
    "bipartite-graph",
    "topological-sort-dfs",
    "topological-sort-kahns",
    "shortest-path-unweighted",
    "dijkstra-algorithm",
    "shortest-path-dag",
    "bellman-ford-algorithm",
    "floyd-warshall-algorithm",
    "mst-kruskal",
    "mst-prim",
    "disjoint-set-union",
    "scc-kosaraju",
    "scc-tarjan",
    "bridges",
    "articulation-points",
    "zero-one-bfs",
    "multi-source-bfs",
    "grid-based-graphs",
    "shortest-path-matrix",
    "rotten-oranges",
    "word-ladder",
    "course-schedule",
    "alien-dictionary",
    "clone-graph",
    "detect-cycle-grid",
    "euler-path-circuit",
    "hamiltonian-path-cycle",
    "graph-coloring",
    "network-flow",
    "transitive-closure",
    "graph-condensation",
    "complexity-graph-algorithms",
  ],
  "dynamic-programming": [
    "introduction-to-dp",
    "recursion-vs-dp",
    "overlapping-subproblems",
    "optimal-substructure",
    "memoization",
    "tabulation",
    "space-optimization",
    "state-definition",
    "transition-relation",
    "base-cases",
    "dp-on-1d-arrays",
    "fibonacci-dp",
    "climbing-stairs",
    "frog-jump",
    "house-robber",
    "min-cost-climbing-stairs",
    "coin-change",
    "perfect-squares",
    "decode-ways",
    "integer-break",
    "dp-on-2d-grids",
    "grid-unique-paths",
    "unique-paths-obstacles",
    "minimum-path-sum",
    "triangle-minimum-path-sum",
    "maximum-path-sum-matrix",
    "cherry-pickup",
    "dp-on-subsequences",
    "subset-sum",
    "partition-equal-subset-sum",
    "count-subsets-sum-k",
    "zero-one-knapsack",
    "unbounded-knapsack",
    "rod-cutting",
    "coin-change-i",
    "coin-change-ii",
    "target-sum",
    "dp-on-strings",
    "longest-common-subsequence",
    "print-lcs",
    "longest-common-substring",
    "shortest-common-supersequence",
    "edit-distance",
    "wildcard-matching",
    "distinct-subsequences",
    "palindrome-partitioning",
    "longest-palindromic-subsequence",
    "dp-on-lis-pattern",
    "longest-increasing-subsequence",
    "print-lis",
    "largest-divisible-subset",
    "longest-string-chain",
    "bitonic-subsequence",
    "number-of-lis",
    "dp-on-stocks",
    "best-time-to-buy-sell-stock-i",
    "best-time-to-buy-sell-stock-ii",
    "stock-with-cooldown",
    "stock-with-transaction-fee",
    "best-time-to-buy-sell-stock-iii",
    "best-time-to-buy-sell-stock-iv",
    "dp-on-partition",
    "matrix-chain-multiplication",
    "burst-balloons",
    "min-cost-cut-stick",
    "boolean-parenthesization",
    "partition-array-max-sum",
    "dp-on-trees",
    "tree-dp-basics",
    "diameter-based-dp",
    "max-path-sum-tree",
    "house-robber-tree",
    "dp-on-graphs",
    "dag-dp",
    "bitmask-dp",
    "tsp",
    "digit-dp",
    "probability-dp",
    "game-theory-dp",
    "interval-dp",
    "state-compression-dp",
    "rerooting-dp",
    "dp-with-binary-search",
    "dp-optimization-techniques",
    "kadanes-algorithm-dp",
    "divide-and-conquer-optimization",
    "knuth-optimization",
    "convex-hull-trick",
    "sos-dp",
    "bitmasking-plus-dp",
    "problem-recognition",
  ],
};

// Lesson display name formatter
function formatLessonName(filename: string): string {
  return filename
    .replace(/\.(jsx|tsx|js|ts)$/, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

// â”€â”€â”€ SERVER-SIDE: reads real filesystem â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export async function getSubjectsFromFS(): Promise<Subject[]> {
  console.log("[Content-Crawl] Starting getSubjectsFromFS...");
  const fs = await import("fs");
  const path = await import("path");

  const contentRoot = path.resolve(process.cwd(), "content");
  console.log(`[Content-Crawl] Root: ${contentRoot}`);

  if (!fs.existsSync(contentRoot)) {
    console.error(`[Content-Crawl] ERROR: Content root NOT FOUND at ${contentRoot}`);
    console.log(`[Content-Crawl] Exiting getSubjectsFromFS due to missing content root.`);
    return [];
  }

  const allFiles = fs.readdirSync(contentRoot);
  console.log(`[Content-Crawl] Found in /content: ${allFiles.join(", ")}`);

  const subjectIds = ["dsa", "artificial-intelligence", "cn", "coa", "os", "digital-electronics", "signals-and-systems", "communication-systems", "dbms", "control-systems", "compiler-design"];
  const subjects: Subject[] = [];

  for (const subjectId of subjectIds) {
    // Find the actual folder name case-insensitively
    const actualFolder = allFiles.find(f => f.toLowerCase() === subjectId.toLowerCase());

    if (!actualFolder) {
      console.warn(`[Content-Crawl] Skipping ${subjectId}: No matching folder found in /content`);
      continue;
    }

    const subjectPath = path.join(contentRoot, actualFolder);

    const meta = SUBJECT_META[subjectId];
    console.log(`[Content-Crawl] Processing Subject: ${subjectId}`);

    const topicDirs = fs
      .readdirSync(subjectPath, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);

    if (TOPIC_ORDER[subjectId]) {
      const order = TOPIC_ORDER[subjectId];
      topicDirs.sort((a, b) => {
        const idxA = order.indexOf(a);
        const idxB = order.indexOf(b);
        if (idxA === -1 && idxB === -1) return 0;
        if (idxA === -1) return 1;
        if (idxB === -1) return -1;
        return idxA - idxB;
      });
    }

    const topics: Topic[] = topicDirs.map((topicId) => {
      const topicPath = path.join(subjectPath, topicId);
      const lessonFiles = fs
        .readdirSync(topicPath)
        .filter((f) => /\.(jsx|tsx|js|ts)$/.test(f));

      const lessons: Lesson[] = lessonFiles.map((file) => ({
        id: file.replace(/\.(jsx|tsx|js|ts)$/, ""),
        name: formatLessonName(file),
        topicId,
        subjectId,
        path: `../content/${subjectId}/${topicId}/${file}`,
      }));

      if (LESSON_ORDER[topicId]) {
        const order = LESSON_ORDER[topicId];
        lessons.sort((a, b) => order.indexOf(a.id) - order.indexOf(b.id));
      }

      return {
        id: topicId,
        name: TOPIC_LABELS[topicId] ?? formatLessonName(topicId),
        description: TOPIC_DESCRIPTIONS[topicId] ?? "A specialized module designed for deep engineering comprehension.",
        subjectId,
        lessons,
      };
    });

    subjects.push({
      id: subjectId,
      name: meta.label,
      description: meta.description,
      icon: meta.icon,
      color: meta.color,
      topics,
    });
  }

  return subjects;
}

export async function getSubjectFromFS(subjectId: string): Promise<Subject | null> {
  const fs = await import("fs");
  const path = await import("path");
  const contentRoot = path.resolve(process.cwd(), "content");

  if (!fs.existsSync(contentRoot)) return null;
  const allFiles = fs.readdirSync(contentRoot);
  const actualFolder = allFiles.find(f => f.toLowerCase() === subjectId.toLowerCase());

  const metaKey = Object.keys(SUBJECT_META).find(k => k.toLowerCase() === subjectId.toLowerCase());
  const meta = metaKey ? SUBJECT_META[metaKey] : null;

  if (!actualFolder || !meta) {
    console.log(`[Content-Registry] getSubjectFromFS(${subjectId}) FAILED: folder=${actualFolder}, meta=${!!meta}`);
    return null;
  }

  const subjectPath = path.join(contentRoot, actualFolder);

  const topicDirs = fs
    .readdirSync(subjectPath, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  console.log(`[Content-Crawl] Subject "${subjectId}" raw topic dirs:`, topicDirs);

  const orderKey = Object.keys(TOPIC_ORDER).find(k => k.toLowerCase() === subjectId.toLowerCase());
  if (orderKey && TOPIC_ORDER[orderKey]) {
    const order = TOPIC_ORDER[orderKey];
    topicDirs.sort((a, b) => {
      const idxA = order.indexOf(a);
      const idxB = order.indexOf(b);
      if (idxA === -1 && idxB === -1) return 0;
      if (idxA === -1) return 1;
      if (idxB === -1) return -1;
      return idxA - idxB;
    });
  }

  const topics: Topic[] = topicDirs.map((topicId) => {
    const topicPath = path.join(subjectPath, topicId);
    const lessonFiles = fs
      .readdirSync(topicPath)
      .filter((f) => /\.(jsx|tsx|js|ts)$/.test(f));

    const lessons: Lesson[] = lessonFiles.map((file) => ({
      id: file.replace(/\.(jsx|tsx|js|ts)$/, ""),
      name: formatLessonName(file),
      topicId,
      subjectId,
      path: `../content/${subjectId}/${topicId}/${file}`,
    }));

    if (LESSON_ORDER[topicId]) {
      const order = LESSON_ORDER[topicId];
      lessons.sort((a, b) => order.indexOf(a.id) - order.indexOf(b.id));
    }

    return {
      id: topicId,
      name: TOPIC_LABELS[topicId] ?? formatLessonName(topicId),
      description: TOPIC_DESCRIPTIONS[topicId] ?? "A specialized module designed for deep engineering comprehension.",
      subjectId,
      lessons,
    };
  });

  return {
    id: actualFolder, // Return actual folder name
    name: meta.label,
    description: meta.description,
    icon: meta.icon,
    color: meta.color,
    topics,
  };
}

export async function getTopicFromFS(subjectId: string, topicId: string): Promise<Topic | null> {
  const subject = await getSubjectFromFS(subjectId);
  const topic = subject?.topics.find((t) => t.id.toLowerCase() === topicId.toLowerCase()) ?? null;
  console.log(`[Content-Registry] Lookup Topic: ${subjectId}/${topicId} -> Found: ${!!topic}`);
  return topic;
}

